"""
Report Generator - 코드 리뷰 리포트 생성기

분석 결과를 마크다운 포맷으로 변환하고 파일로 저장합니다.
"""

from pathlib import Path
from datetime import datetime
from typing import Optional, List
import logging

from app.models.language import Language
from app.models.review_category import ReviewCategory

logger = logging.getLogger(__name__)


class ReportGenerator:
    """코드 리뷰 리포트 생성기

    분석 결과를 구조화된 마크다운 포맷으로 변환합니다.

    Examples:
        >>> generator = ReportGenerator()
        >>> report = generator.generate_report(
        ...     code="def hello(): pass",
        ...     language=Language.PYTHON,
        ...     review_result="# Review\n\nGood code",
        ...     categories=[ReviewCategory.NULL_SAFETY],
        ...     model="gpt-4o-mini"
        ... )
        >>> print(report)
    """

    def __init__(self, reports_dir: Optional[Path] = None):
        """초기화

        Args:
            reports_dir: 리포트 저장 디렉토리 (기본: 프로젝트 루트/reports)
        """
        if reports_dir is None:
            # 프로젝트 루트 찾기
            project_root = Path(__file__).parent.parent.parent
            reports_dir = project_root / "reports"

        self.reports_dir = Path(reports_dir)
        self.reports_dir.mkdir(parents=True, exist_ok=True)

        logger.info(f"ReportGenerator initialized with dir: {self.reports_dir}")

    def generate_report(
        self,
        code: str,
        language: Language,
        review_result: str,
        categories: List[ReviewCategory],
        model: str,
        input_tokens: int = 0,
        output_tokens: int = 0,
        cost_usd: float = 0.0,
        cost_krw: float = 0.0,
        additional_info: Optional[dict] = None,
    ) -> str:
        """리포트 생성 (마크다운)

        Args:
            code: 분석한 코드
            language: 프로그래밍 언어
            review_result: LLM 리뷰 결과 (마크다운)
            categories: 선택된 리뷰 카테고리
            model: 사용된 모델 이름
            input_tokens: 입력 토큰 수
            output_tokens: 출력 토큰 수
            cost_usd: 비용 (USD)
            cost_krw: 비용 (KRW)
            additional_info: 추가 정보 (옵션)

        Returns:
            마크다운 포맷 리포트

        Examples:
            >>> generator = ReportGenerator()
            >>> report = generator.generate_report(
            ...     code="print('hello')",
            ...     language=Language.PYTHON,
            ...     review_result="# Good code",
            ...     categories=[ReviewCategory.NULL_SAFETY],
            ...     model="gpt-4o-mini",
            ...     input_tokens=100,
            ...     output_tokens=200
            ... )
        """
        timestamp = datetime.now()

        # 헤더 생성
        header = self._generate_header(
            timestamp, language, model, categories, input_tokens, output_tokens, cost_usd, cost_krw
        )

        # 코드 섹션
        code_section = self._generate_code_section(code, language)

        # 리뷰 결과 섹션
        review_section = self._generate_review_section(review_result)

        # 푸터
        footer = self._generate_footer(timestamp)

        # 전체 리포트 조합
        report = f"{header}\n\n{code_section}\n\n{review_section}\n\n{footer}"

        logger.info(f"Report generated ({len(report)} chars)")

        return report

    def _generate_header(
        self,
        timestamp: datetime,
        language: Language,
        model: str,
        categories: List[ReviewCategory],
        input_tokens: int,
        output_tokens: int,
        cost_usd: float,
        cost_krw: float,
    ) -> str:
        """리포트 헤더 생성"""
        category_names = ", ".join([cat.value for cat in categories])

        header = f"""# 코드 리뷰 리포트

**생성 일시**: {timestamp.strftime("%Y-%m-%d %H:%M:%S")}  
**프로그래밍 언어**: {language.value}  
**분석 모델**: {model}  
**리뷰 카테고리**: {category_names}

## 비용 정보

- **Input Tokens**: {input_tokens:,}
- **Output Tokens**: {output_tokens:,}
- **Total Tokens**: {(input_tokens + output_tokens):,}
- **Cost (USD)**: ${cost_usd:.6f}
- **Cost (KRW)**: ₩{cost_krw:.2f}

---
"""
        return header

    def _generate_code_section(self, code: str, language: Language) -> str:
        """코드 섹션 생성"""
        section = f"""## 분석 대상 코드

```{language.value}
{code}
```
"""
        return section

    def _generate_review_section(self, review_result: str) -> str:
        """리뷰 결과 섹션 생성"""
        section = f"""## 리뷰 결과

{review_result}
"""
        return section

    def _generate_footer(self, timestamp: datetime) -> str:
        """리포트 푸터 생성"""
        footer = f"""---

*Report generated by Code Review Assistant*  
*{timestamp.strftime("%Y-%m-%d %H:%M:%S")}*
"""
        return footer

    def save_report(
        self,
        report: str,
        filename: Optional[str] = None,
        language: Optional[Language] = None,
    ) -> Path:
        """리포트를 파일로 저장

        Args:
            report: 마크다운 리포트
            filename: 파일명 (옵션, 기본: 타임스탬프 기반)
            language: 언어 (파일명에 포함)

        Returns:
            저장된 파일 경로

        Examples:
            >>> generator = ReportGenerator()
            >>> report = "# Test Report"
            >>> path = generator.save_report(report, language=Language.PYTHON)
            >>> print(path)
            /path/to/reports/python_20240101_120000.md
        """
        # 파일명 생성
        if filename is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            lang_prefix = language.value if language else "unknown"
            filename = f"{lang_prefix}_{timestamp}.md"

        # .md 확장자 보장
        if not filename.endswith(".md"):
            filename += ".md"

        # 파일 경로
        file_path = self.reports_dir / filename

        # 파일 저장
        file_path.write_text(report, encoding="utf-8")

        logger.info(f"Report saved to: {file_path}")

        return file_path

    def get_reports_dir(self) -> Path:
        """리포트 디렉토리 경로 반환

        Returns:
            리포트 디렉토리 경로
        """
        return self.reports_dir

    def list_reports(self, language: Optional[Language] = None) -> List[Path]:
        """저장된 리포트 목록 조회

        Args:
            language: 특정 언어로 필터링 (옵션)

        Returns:
            리포트 파일 경로 리스트 (최신순)

        Examples:
            >>> generator = ReportGenerator()
            >>> reports = generator.list_reports(language=Language.PYTHON)
            >>> print(len(reports))
            5
        """
        # 모든 .md 파일 찾기
        pattern = f"{language.value}_*.md" if language else "*.md"
        reports = list(self.reports_dir.glob(pattern))

        # 수정 시간 기준 역순 정렬 (최신순)
        reports.sort(key=lambda p: p.stat().st_mtime, reverse=True)

        logger.debug(f"Found {len(reports)} reports (filter: {pattern})")

        return reports

    def delete_report(self, file_path: Path) -> bool:
        """리포트 파일 삭제

        Args:
            file_path: 삭제할 파일 경로

        Returns:
            True if deleted successfully

        Examples:
            >>> generator = ReportGenerator()
            >>> success = generator.delete_report(Path("reports/python_20240101.md"))
        """
        try:
            file_path.unlink()
            logger.info(f"Report deleted: {file_path}")
            return True
        except Exception as e:
            logger.error(f"Failed to delete report: {e}")
            return False


# 모듈 레벨 export
__all__ = ["ReportGenerator"]
